--- #YAML:1.0
name:                Lyrics-Fetcher-AstraWeb
version:             0.3
abstract:            Get song lyrics from lyrics.astraweb.com
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    WWW::Mechanize:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Precious <davidp@preshweb.co.uk>
